var namespacetorc_1_1router =
[
    [ "NetRouter", "d5/d60/classtorc_1_1router_1_1NetRouter.html", "d5/d60/classtorc_1_1router_1_1NetRouter" ],
    [ "NetRouterBase", "d5/dd4/classtorc_1_1router_1_1NetRouterBase.html", "d5/dd4/classtorc_1_1router_1_1NetRouterBase" ],
    [ "NetRouterHeuristic", "d9/d5b/classtorc_1_1router_1_1NetRouterHeuristic.html", "d9/d5b/classtorc_1_1router_1_1NetRouterHeuristic" ],
    [ "NetRouterHeuristicBase", "dc/d3d/classtorc_1_1router_1_1NetRouterHeuristicBase.html", "dc/d3d/classtorc_1_1router_1_1NetRouterHeuristicBase" ],
    [ "NetVectorRouterBase", "de/de8/classtorc_1_1router_1_1NetVectorRouterBase.html", "de/de8/classtorc_1_1router_1_1NetVectorRouterBase" ],
    [ "NetVectorRouterHeuristicBase", "d9/db9/classtorc_1_1router_1_1NetVectorRouterHeuristicBase.html", "d9/db9/classtorc_1_1router_1_1NetVectorRouterHeuristicBase" ],
    [ "TilewireData", "da/dd5/structtorc_1_1router_1_1TilewireData.html", "da/dd5/structtorc_1_1router_1_1TilewireData" ],
    [ "PathFinder", "d4/d6a/classtorc_1_1router_1_1PathFinder.html", "d4/d6a/classtorc_1_1router_1_1PathFinder" ],
    [ "PathFinderHeuristic", "de/d03/classtorc_1_1router_1_1PathFinderHeuristic.html", "de/d03/classtorc_1_1router_1_1PathFinderHeuristic" ],
    [ "PathFinderNetRouterHeuristic", "dc/d58/classtorc_1_1router_1_1PathFinderNetRouterHeuristic.html", "dc/d58/classtorc_1_1router_1_1PathFinderNetRouterHeuristic" ],
    [ "RouteNet", "d6/d37/classtorc_1_1router_1_1RouteNet.html", "d6/d37/classtorc_1_1router_1_1RouteNet" ],
    [ "RouteNode", "d0/d48/classtorc_1_1router_1_1RouteNode.html", "d0/d48/classtorc_1_1router_1_1RouteNode" ],
    [ "RouteNodePtrCostCompare", "d0/d58/classtorc_1_1router_1_1RouteNodePtrCostCompare.html", "d0/d58/classtorc_1_1router_1_1RouteNodePtrCostCompare" ],
    [ "RouterHeuristicBase", "d5/df5/classtorc_1_1router_1_1RouterHeuristicBase.html", "d5/df5/classtorc_1_1router_1_1RouterHeuristicBase" ],
    [ "RouterStatistics", "d1/de4/structtorc_1_1router_1_1RouterStatistics.html", "d1/de4/structtorc_1_1router_1_1RouterStatistics" ],
    [ "RouteTreeNode", "d2/de5/classtorc_1_1router_1_1RouteTreeNode.html", "d2/de5/classtorc_1_1router_1_1RouteTreeNode" ],
    [ "RouteUtilities", "d4/d26/classtorc_1_1router_1_1RouteUtilities.html", "d4/d26/classtorc_1_1router_1_1RouteUtilities" ],
    [ "Trace", "d5/da9/classtorc_1_1router_1_1Trace.html", "d5/da9/classtorc_1_1router_1_1Trace" ],
    [ "TraceNode", "d1/dba/classtorc_1_1router_1_1TraceNode.html", "d1/dba/classtorc_1_1router_1_1TraceNode" ],
    [ "TraceVirtex5TestFixture", "da/d1c/structtorc_1_1router_1_1TraceVirtex5TestFixture.html", "da/d1c/structtorc_1_1router_1_1TraceVirtex5TestFixture" ],
    [ "TraceVirtexTristateTestFixture", "df/dc6/structtorc_1_1router_1_1TraceVirtexTristateTestFixture.html", "df/dc6/structtorc_1_1router_1_1TraceVirtexTristateTestFixture" ],
    [ "TraceUnitTestFixture", "d1/d2c/structtorc_1_1router_1_1TraceUnitTestFixture.html", "d1/d2c/structtorc_1_1router_1_1TraceUnitTestFixture" ],
    [ "Unrouter", "db/dfa/classtorc_1_1router_1_1Unrouter.html", "db/dfa/classtorc_1_1router_1_1Unrouter" ],
    [ "TracerTestFixture", "da/def/structtorc_1_1router_1_1TracerTestFixture.html", "da/def/structtorc_1_1router_1_1TracerTestFixture" ]
];