var namespacetorc_1_1architecture =
[
    [ "architecture", "d3/db3/namespacetorc_1_1architecture_1_1architecture.html", null ],
    [ "xilinx", "da/d49/namespacetorc_1_1architecture_1_1xilinx.html", "da/d49/namespacetorc_1_1architecture_1_1xilinx" ],
    [ "Arc", "d8/d60/classtorc_1_1architecture_1_1Arc.html", "d8/d60/classtorc_1_1architecture_1_1Arc" ],
    [ "InvalidArcException", "d4/dbb/classtorc_1_1architecture_1_1InvalidArcException.html", "d4/dbb/classtorc_1_1architecture_1_1InvalidArcException" ],
    [ "ArcUsage", "da/d84/classtorc_1_1architecture_1_1ArcUsage.html", "da/d84/classtorc_1_1architecture_1_1ArcUsage" ],
    [ "Array", "db/d9f/classtorc_1_1architecture_1_1Array.html", "db/d9f/classtorc_1_1architecture_1_1Array" ],
    [ "Array2D", "d3/d8f/classtorc_1_1architecture_1_1Array2D.html", "d3/d8f/classtorc_1_1architecture_1_1Array2D" ],
    [ "DDB", "d6/d22/classtorc_1_1architecture_1_1DDB.html", "d6/d22/classtorc_1_1architecture_1_1DDB" ],
    [ "DDBConsoleStreams", "d7/d8d/classtorc_1_1architecture_1_1DDBConsoleStreams.html", "d7/d8d/classtorc_1_1architecture_1_1DDBConsoleStreams" ],
    [ "DDBStreamHelper", "d6/d64/classtorc_1_1architecture_1_1DDBStreamHelper.html", "d6/d64/classtorc_1_1architecture_1_1DDBStreamHelper" ],
    [ "DigestStream", "d0/d83/classtorc_1_1architecture_1_1DigestStream.html", "d0/d83/classtorc_1_1architecture_1_1DigestStream" ],
    [ "ExtendedWireInfo", "de/d46/classtorc_1_1architecture_1_1ExtendedWireInfo.html", "de/d46/classtorc_1_1architecture_1_1ExtendedWireInfo" ],
    [ "InstancePin", "dd/d5d/classtorc_1_1architecture_1_1InstancePin.html", "dd/d5d/classtorc_1_1architecture_1_1InstancePin" ],
    [ "Package", "df/d70/classtorc_1_1architecture_1_1Package.html", "df/d70/classtorc_1_1architecture_1_1Package" ],
    [ "Pad", "d2/dc3/classtorc_1_1architecture_1_1Pad.html", "d2/dc3/classtorc_1_1architecture_1_1Pad" ],
    [ "PrimitiveConn", "d0/df5/classtorc_1_1architecture_1_1PrimitiveConn.html", "d0/df5/classtorc_1_1architecture_1_1PrimitiveConn" ],
    [ "PrimitiveDef", "d5/da4/classtorc_1_1architecture_1_1PrimitiveDef.html", "d5/da4/classtorc_1_1architecture_1_1PrimitiveDef" ],
    [ "PrimitiveElement", "dc/d9a/classtorc_1_1architecture_1_1PrimitiveElement.html", "dc/d9a/classtorc_1_1architecture_1_1PrimitiveElement" ],
    [ "PrimitiveElementPin", "da/df9/classtorc_1_1architecture_1_1PrimitiveElementPin.html", "da/df9/classtorc_1_1architecture_1_1PrimitiveElementPin" ],
    [ "PinDirection", "df/dbb/classtorc_1_1architecture_1_1PinDirection.html", "df/dbb/classtorc_1_1architecture_1_1PinDirection" ],
    [ "PrimitivePin", "d5/d69/classtorc_1_1architecture_1_1PrimitivePin.html", "d5/d69/classtorc_1_1architecture_1_1PrimitivePin" ],
    [ "Segments", "db/dcc/classtorc_1_1architecture_1_1Segments.html", "db/dcc/classtorc_1_1architecture_1_1Segments" ],
    [ "segments_regression_test_helper", "d2/d42/classtorc_1_1architecture_1_1segments__regression__test__helper.html", "d2/d42/classtorc_1_1architecture_1_1segments__regression__test__helper" ],
    [ "segments_unit_test_helper", "d4/da3/classtorc_1_1architecture_1_1segments__unit__test__helper.html", "d4/da3/classtorc_1_1architecture_1_1segments__unit__test__helper" ],
    [ "Site", "da/dd8/classtorc_1_1architecture_1_1Site.html", "da/dd8/classtorc_1_1architecture_1_1Site" ],
    [ "Sites", "db/db7/classtorc_1_1architecture_1_1Sites.html", "db/db7/classtorc_1_1architecture_1_1Sites" ],
    [ "TileInfo", "d0/d83/classtorc_1_1architecture_1_1TileInfo.html", "d0/d83/classtorc_1_1architecture_1_1TileInfo" ],
    [ "Tiles", "d8/dc4/classtorc_1_1architecture_1_1Tiles.html", "d8/dc4/classtorc_1_1architecture_1_1Tiles" ],
    [ "Tilewire", "d6/d19/classtorc_1_1architecture_1_1Tilewire.html", "d6/d19/classtorc_1_1architecture_1_1Tilewire" ],
    [ "Versions", "d9/db0/classtorc_1_1architecture_1_1Versions.html", "d9/db0/classtorc_1_1architecture_1_1Versions" ],
    [ "VprExporter", "da/dc5/classtorc_1_1architecture_1_1VprExporter.html", "da/dc5/classtorc_1_1architecture_1_1VprExporter" ],
    [ "WireArray", "d0/d12/classtorc_1_1architecture_1_1WireArray.html", "d0/d12/classtorc_1_1architecture_1_1WireArray" ],
    [ "WireInfo", "d3/d5f/classtorc_1_1architecture_1_1WireInfo.html", "d3/d5f/classtorc_1_1architecture_1_1WireInfo" ],
    [ "WireUsage", "dd/d65/classtorc_1_1architecture_1_1WireUsage.html", "dd/d65/classtorc_1_1architecture_1_1WireUsage" ],
    [ "XdlImporter", "d2/d42/classtorc_1_1architecture_1_1XdlImporter.html", "d2/d42/classtorc_1_1architecture_1_1XdlImporter" ]
];